"""empty message

Revision ID: b85178f7fbdc
Revises: e27909fd77cd
Create Date: 2018-03-19 18:19:24.386959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85178f7fbdc'
down_revision = 'e27909fd77cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_info', sa.Column('ImpDate', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_info', 'ImpDate')
    # ### end Alembic commands ###
